'use client';
import Link from 'next/link';
import { useEffect, useId, useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, ArrowDown, Fingerprint, FileText, Link2, ScanText, Moon, Sun, CreditCard, ShieldCheck, Plus, ExternalLink } from 'lucide-react';
import { useWorkspace } from './workspace-provider';
import { AuthProofScene } from './auth-proof-scene';
import { NavigationGlyph } from './navigation-glyph';
import { LandingMeshShader } from './landing-mesh-shader';
const navigation=[['how-it-works','How it works'],['payments','Payments'],['evidence','Evidence'],['faq','FAQs']];
function GeometricSurface({kind='scales'}:{kind?:'scales'|'facets'|'diamonds'}) {
 const id=useId();
 const shape=kind==='scales'?{width:48,height:32,path:'M-24 0Q0 32 24 0Q48 32 72 0M0 16Q24 48 48 16'}:
  kind==='facets'?{width:64,height:56,path:'M0 0L32 28L64 0M0 56L32 28L64 56M32 0V56'}:
  {width:40,height:40,path:'M20 0L40 20L20 40L0 20ZM0 0L40 40M40 0L0 40'};
 return <svg className={`landing-geometric landing-geometric-${kind}`} aria-hidden="true" focusable="false" width="100%" height="100%"><defs><pattern id={id} width={shape.width} height={shape.height} patternUnits="userSpaceOnUse"><path d={shape.path} fill="none" stroke="currentColor" strokeWidth=".7"/></pattern></defs><rect width="100%" height="100%" fill={`url(#${id})`}/></svg>;
}
const faqs=[
 ['How do I actually receive a payment?','Connect a PayPal sandbox app linked to your business sandbox account in Account settings. Create a project and generate its payment link. The client opens the link, approves with a personal sandbox account, then completes the capture. PayPal records the transaction in your business sandbox account.'],
 ['Does the hackathon demo move real money?','No. This build uses the PayPal sandbox. It makes real sandbox API requests with test funds. Your normal PayPal balance is not affected, and live merchant onboarding is not implemented.'],
 ['What does Gemini do beyond writing a response?','Gemini analyses the original records you select, returns findings tied to evidence IDs, and identifies missing evidence. The server rejects unknown citations. You still review every statement: a valid citation is not a guarantee that a claim is correct.'],
 ['Does a delivery link prove the client received the work?','No. A seller-saved link, a client page visit, and an explicit acknowledgement mean different things. DeliveryProof preserves the distinction instead of inventing acceptance. Client acknowledgement collection is a next step; this build does not simulate it.'],
 ['Does DeliveryProof guarantee that I win a dispute?','No. It helps organise records and prepare a reviewed response. It does not determine eligibility for Seller Protection, make legal findings, or guarantee a dispute outcome.'],
 ['What is ready to try right now?','Accounts, persistent projects, seller-entered delivery records, PayPal sandbox order and capture flows, Gemini analysis, and reviewed JSON packets. UploadThing has an authenticated server endpoint; upload UI, automatic Elastic indexing, and direct PayPal evidence submission remain integration work.'],
];
export function LandingPage(){
 const {user,theme,toggleTheme}=useWorkspace();const [menu,setMenu]=useState(false);const [scrolled,setScrolled]=useState(false);const [active,setActive]=useState('');
 const root=useRef<HTMLElement>(null);
 useEffect(()=>{
  const page=root.current;if(!page)return;
  let frame=0;
  const update=()=>{frame=0;setScrolled(window.scrollY>24);};
  const scroll=()=>{if(!frame)frame=requestAnimationFrame(update);};update();window.addEventListener('scroll',scroll,{passive:true});window.addEventListener('resize',scroll);
  const observer=new IntersectionObserver(entries=>{entries.forEach(entry=>{entry.target.setAttribute('data-in-view',String(entry.isIntersecting));if(entry.isIntersecting){entry.target.setAttribute('data-revealed','true');if(entry.target.id)setActive(entry.target.id);}});},{rootMargin:'0px 0px -8% 0px',threshold:.08});
  page.querySelectorAll('.landing-reveal').forEach(element=>observer.observe(element));
  const reveal=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-shown');reveal.unobserve(entry.target);}});},{rootMargin:'0px 0px -24px 0px',threshold:.08});
  const selectors=['.landing-nav','.landing-hero > div:first-child > *','.landing-art','.landing-ticker','.landing-section-head > *','.landing-feature-grid article','.landing-payment-section > div:first-child > *','.landing-payment-step','.landing-step-connector','.landing-source-chip','.landing-ai-result','.landing-evidence-section > div:last-child > :not(ul)','.landing-evidence-points li','.landing-faq details','.landing-final > *','.landing-footer'];
  page.querySelectorAll<HTMLElement>(selectors.join(',')).forEach(element=>{
    element.classList.add('landing-enter');
    const siblings=Array.from(element.parentElement?.children||[]);element.style.setProperty('--landing-enter-delay',`${Math.min(siblings.indexOf(element),4)*60}ms`);
    reveal.observe(element);
  });
  page.setAttribute('data-motion-ready','true');
  return()=>{window.removeEventListener('scroll',scroll);window.removeEventListener('resize',scroll);cancelAnimationFrame(frame);observer.disconnect();reveal.disconnect();};
 },[]);
 const target=user?'/dashboard':'/signup';
 return <main ref={root} className="landing-page landing-alive">
  <div className="landing-flow-art" aria-hidden="true"><svg viewBox="0 0 1200 2300" preserveAspectRatio="none" fill="none"><path className="landing-flow-track" id="landing-trail" d="M1100 10V280Q1100 380 1000 380H960Q860 380 860 480V650Q860 750 760 750H110Q70 750 70 850V1040Q70 1140 170 1140H1020Q1130 1140 1130 1250V1480Q1130 1580 1030 1580H970Q850 1580 850 1700V1990Q850 2130 710 2130H240"/><path className="landing-flow-current" d="M1100 10V280Q1100 380 1000 380H960Q860 380 860 480V650Q860 750 760 750H110Q70 750 70 850V1040Q70 1140 170 1140H1020Q1130 1140 1130 1250V1480Q1130 1580 1030 1580H970Q850 1580 850 1700V1990Q850 2130 710 2130H240"/><g className="landing-traveller"><circle r="3" fill="#af8850"><animateMotion dur="24s" repeatCount="indefinite"><mpath href="#landing-trail"/></animateMotion></circle><circle r="3" fill="#af8850" opacity=".5"><animateMotion dur="24s" begin="-12s" repeatCount="indefinite"><mpath href="#landing-trail"/></animateMotion></circle></g></svg></div>
  <header className="landing-header" data-scrolled={scrolled}><div className="landing-nav-surface" aria-hidden="true" style={{backdropFilter:scrolled?"blur(24px) saturate(130%)":undefined,WebkitBackdropFilter:scrolled?"blur(24px) saturate(130%)":undefined}}/><nav className="landing-nav" aria-label="Main navigation"><Link href="/" className="flex items-center gap-3 text-sm font-semibold"><span className="auth-brand"><Fingerprint size={22}/></span>DeliveryProof</Link><div className="landing-nav-links">{navigation.map(([id,label])=><a href={'#'+id} key={id} aria-current={active===id?'location':undefined}>{label}</a>)}</div><div className="flex items-center gap-4"><button className="auth-icon" onClick={toggleTheme} aria-label={`Switch to ${theme==='light'?'dark':'light'} mode`}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button><Link className="landing-nav-account" href={user?'/dashboard':'/signin'}>{user?'Workspace':'Sign in'}<ArrowRight size={14}/></Link><button className="landing-menu-button auth-icon" aria-label={menu?'Close navigation':'Open navigation'} aria-expanded={menu} aria-controls="landing-mobile-nav" onClick={()=>setMenu(v=>!v)}><NavigationGlyph open={menu}/></button></div></nav><div className="landing-mobile-wrap" data-open={menu}><nav id="landing-mobile-nav" aria-label="Mobile navigation" inert={!menu}>{navigation.map(([id,label])=><a href={'#'+id} key={id} onClick={()=>setMenu(false)}>{label}<ArrowRight size={14}/></a>)}</nav></div></header>
  <section className="landing-hero"><div><p className="landing-hackathon"><span/> BUILT FOR THE PAYPAL AI HACKATHON <ArrowRight size={12}/></p><h1>You delivered.<br/><span>Keep the proof.</span></h1><p className="landing-description">Getting paid is one part of the story.<br/>Preserve the agreement, the payment, and the handover—then build an evidence-backed response when it matters.</p><div className="landing-actions"><Link className="auth-submit" href={target}><span>{user?'Open your workspace':'Start your delivery story'}</span><ArrowRight size={18}/></Link><a className="landing-explore" href="#how-it-works">Explore the flow <ArrowDown size={14} aria-hidden="true"/></a></div><div className="landing-hero-details"><span><CreditCard size={13}/>PayPal sandbox</span><span><ScanText size={13}/>Gemini evidence review</span></div></div><div className="landing-art"><GeometricSurface kind="facets"/><LandingMeshShader dark={theme === 'dark'}/><span className="landing-art-label">FROM WORK SENT TO EVIDENCE KEPT</span><AuthProofScene/><span className="landing-art-footer">A record, not a guess.</span></div></section>
  <div className="landing-ticker" aria-hidden="true"><div>{[0,1].map(copy=><span key={copy}>AGREE <ArrowUpRight size={25} strokeWidth={1.2} aria-hidden="true"/> GET PAID <ArrowUpRight size={25} strokeWidth={1.2} aria-hidden="true"/> DELIVER <ArrowUpRight size={25} strokeWidth={1.2} aria-hidden="true"/> PRESERVE <ArrowUpRight size={25} strokeWidth={1.2} aria-hidden="true"/> REVIEW <ArrowUpRight size={25} strokeWidth={1.2} aria-hidden="true"/></span>)}</div></div>
  <section className="landing-features landing-reveal" id="how-it-works"><div className="landing-section-head"><span className="auth-eyebrow">01 / THE FLOW</span><h2>Good work shouldn't end<br/><span>in a missing paper trail.</span></h2><p className="landing-section-description">A connected workflow for freelancers and small studios delivering digital work.</p></div><div className="landing-feature-grid">{[{icon:FileText,title:'Agree on the work.',text:'Save the scope, client, and amount. Your original record becomes the first part of the story.'},{icon:CreditCard,title:'Get paid through PayPal.',text:'Send a sandbox payment link. The server verifies the capture and preserves its order, amount, and project reference.'},{icon:Link2,title:'Keep the handover.',text:'Save the delivery link and retain its history. Keep seller records distinct from actual client receipt.'}].map(({icon:Icon,title,text},index)=><article key={title} style={{'--reveal-index':index} as React.CSSProperties}><div className="landing-feature-top"><Icon size={23} strokeWidth={1.4}/><span>0{index+1}</span></div><h3>{title}</h3><p>{text}</p><div className="landing-feature-line"><span/></div><GeometricSurface kind={index===0?"scales":index===1?"diamonds":"facets"}/></article>)}</div></section>
  <section className="landing-payment-section landing-reveal" id="payments"><div><span className="auth-eyebrow">02 / FOLLOW THE MONEY</span><h2>From their approval.<br/><span>To your account.</span></h2><p className="landing-section-description">A payment link is the beginning. A verified capture is the receipt.</p><a href="https://developer.paypal.com/dashboard/accounts" target="_blank" rel="noreferrer" className="landing-external">Set up sandbox accounts<ExternalLink size={13}/></a></div><div className="landing-payment-diagram"><GeometricSurface kind="scales"/><div className="landing-payment-step"><span className="landing-step-icon"><Fingerprint size={20}/></span><div><strong>Your business sandbox</strong><small>Connect the app in Account settings.</small></div><span>01</span></div><div className="landing-step-connector"><svg viewBox="0 0 340 36"><path d="M24 0v16q0 8 8 8h276q8 0 8 8v4" pathLength="1"/></svg><span>Share the project payment link</span></div><div className="landing-payment-step"><span className="landing-step-icon"><CreditCard size={20}/></span><div><strong>Client approves in PayPal</strong><small>A separate personal sandbox account.</small></div><span>02</span></div><div className="landing-step-connector"><svg viewBox="0 0 340 36"><path d="M24 0v16q0 8 8 8h276q8 0 8 8v4" pathLength="1"/></svg><span>Complete & verify the capture</span></div><div className="landing-payment-step landing-step-confirmed"><span className="landing-step-icon"><ShieldCheck size={20}/></span><div><strong>Payment recorded</strong><small>Test funds in your business sandbox.</small></div><span>03</span></div><p className="caption mt-5">Sandbox only. No real funds or live settlement.</p></div></section>
  <section className="landing-evidence-section landing-reveal" id="evidence"><div className="landing-evidence-visual" aria-hidden="true"><GeometricSurface kind="diamonds"/><div className="landing-source-chip"><FileText size={15}/>Agreement<span>SOURCE 01</span></div><div className="landing-source-chip"><CreditCard size={15}/>PayPal capture<span>SOURCE 02</span></div><div className="landing-source-chip"><Link2 size={15}/>Delivery link<span>SOURCE 03</span></div><svg viewBox="0 0 340 64"><path d="M50 0v24q0 8 8 8h104q8 0 8 8v24M290 0v24q0 8-8 8H178q-8 0-8 8v24"/></svg><div className="landing-ai-result"><span><ScanText size={18}/>GEMINI REVIEW</span><strong>Claims with a source.<br/>Gaps left visible.</strong><p>Selected evidence → structured findings → your review</p><span className="landing-citation">Human review comes next <ArrowRight size={13}/></span></div></div><div><span className="auth-eyebrow">03 / AI WITH A JOB TO DO</span><h2>More than a draft.<br/><span>An evidence check.</span></h2><p className="landing-section-description">Gemini works on your selected records. It links findings to evidence IDs and calls out what's missing, so an incomplete trail stays visibly incomplete.</p><ul className="landing-evidence-points"><li><ShieldCheck size={16}/>Unknown citations are rejected on the server.</li><li><FileText size={16}/>Original records stay separate from generated text.</li><li><Fingerprint size={16}/>You review the claims before preparing a packet.</li></ul><p className="landing-small">No automatic dispute submissions. No promised outcomes.</p></div></section>
  <section className="landing-faq landing-reveal" id="faq"><div className="landing-section-head"><span className="auth-eyebrow">A FEW CLEAR ANSWERS</span><h2>Before you begin.</h2><p className="landing-section-description">The payment, the proof, and the prototype.</p></div><div>{faqs.map(([question,answer])=><details key={question}><summary>{question}<Plus size={17}/></summary><div className="landing-faq-answer"><p>{answer}</p></div></details>)}</div></section>
  <section className="landing-final landing-reveal"><Fingerprint size={32} strokeWidth={1.3}/><h2>Get the work done.<br/><span>Keep its story together.</span></h2><Link className="auth-submit" href={target}><span>{user?'Back to your workspace':'Create your workspace'}</span><ArrowRight size={16}/></Link></section><footer className="landing-footer"><Link href="/">DeliveryProof</Link><span>PayPal AI Hackathon · Sandbox prototype</span><a href="https://github.com/HarshitKumar9030/deliveryproof" target="_blank" rel="noreferrer">Explore the code <ArrowUpRight size={13} aria-hidden="true"/></a></footer>
 </main>;
}
