'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { CheckCircle2, CreditCard } from 'lucide-react';
export function MerchantConnection() {
  const [connected,setConnected]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{const controller=new AbortController();fetch('/api/paypal/connection',{signal:controller.signal}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);setConnected(result.connected);}).catch(error=>{if(!controller.signal.aborted)setError(error.message);});return()=>controller.abort();},[]);
  async function connect(event:FormEvent<HTMLFormElement>){event.preventDefault();if(busy)return;const form=event.currentTarget;const data=new FormData(form);setBusy(true);setError('');try{const response=await fetch('/api/paypal/connection',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clientId:data.get('clientId'),clientSecret:data.get('clientSecret')})});const result=await response.json();if(!response.ok)throw new Error(result.error);setConnected(true);form.reset();}catch(error){setError(error instanceof Error?error.message:'Could not connect');}finally{setBusy(false);}}
  return <section className="squircle mt-6 max-w-xl rounded-[30px] bg-paper p-7 sm:p-9"><div className="mb-5 flex items-center gap-3"><CreditCard size={22}/><h2>Receive PayPal payments.</h2></div><p className="muted text-sm leading-7">Connect a sandbox app linked to your business test account. Your client pays with a separate personal sandbox account; the captured test funds go to your business sandbox account.</p>{connected&&<p className="my-5 flex items-center gap-2 text-sm"><CheckCircle2 size={17}/>Sandbox app connected</p>}<form onSubmit={connect} className="form-stack mt-6"><label>Sandbox Client ID<input name="clientId" required minLength={10} maxLength={512} autoComplete="off"/></label><label>Sandbox Client Secret<input name="clientSecret" type="password" required minLength={10} maxLength={512} autoComplete="off"/></label>{error&&<p role="alert" className="form-error">{error}</p>}<button className="button primary" disabled={busy}>{busy?'Checking connection…':connected?'Update sandbox connection':'Connect sandbox app'}</button></form><a href="https://developer.paypal.com/dashboard/applications/sandbox" target="_blank" rel="noreferrer" className="text-button mt-5">Get credentials from PayPal Developer ↗</a><p className="caption mt-4">Credentials are encrypted on the server and belong only to your account. Sandbox payments use test funds.</p></section>;
}
