'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { CheckCircle2, CreditCard } from 'lucide-react';
type Payment={title:string;client:string;amount:string;paid:boolean;approvalUrl:string};
export function PaymentCheckout({token}:{token:string}) {
  const [payment,setPayment]=useState<Payment|null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{const controller=new AbortController(); fetch('/api/pay/'+token,{signal:controller.signal}).then(async response=>{const result=await response.json();if(!response.ok)throw new Error(result.error);setPayment(result);}).catch(error=>{if(!controller.signal.aborted)setError(error.message);});return()=>controller.abort();},[token]);
  async function capture(){if(busy)return;setBusy(true);setError('');try{const response=await fetch('/api/pay/'+token,{method:'POST'});const result=await response.json();if(!response.ok)throw new Error(result.error);setPayment(p=>p?{...p,paid:true}:p);}catch(error){setError(error instanceof Error?error.message:'Unable to verify payment');}finally{setBusy(false);}}
  return <main className="grid min-h-dvh place-items-center bg-canvas px-6 py-12"><section className="squircle w-full max-w-md rounded-[32px] bg-paper p-8"><Link href="/" className="caption">DeliveryProof</Link><div className="mt-8 mb-5">{payment?.paid?<CheckCircle2 size={30}/>:<CreditCard size={30}/>}</div><h1 className="text-3xl tracking-tight">{payment?.paid?'Payment confirmed.':'A clear next step.'}</h1>{payment?<><p className="mt-5 text-muted">{payment.title} · {payment.client}</p><p className="my-6 text-4xl tracking-tight">${payment.amount}<span className="ml-2 text-sm text-muted">USD</span></p>{!payment.paid&&<div className="grid gap-3"><p className="rounded-2xl bg-surface px-4 py-3 text-xs leading-6 text-muted">In PayPal, choose Log in and use a Personal sandbox account. Do not use the seller’s Business account or enter a real card. Find test credentials in PayPal Developer → Testing Tools → Sandbox Accounts.</p><a className="button primary" href={payment.approvalUrl}>1. Approve in PayPal</a><button className="button secondary" disabled={busy} onClick={capture}>{busy?'Verifying capture…':'2. Complete & verify payment'}</button></div>}<p className="caption mt-6">PayPal sandbox · Test funds only. The seller receives the capture in the business sandbox account associated with their connected app.</p></>:!error&&<p role="status" className="mt-6">Loading payment…</p>}{error&&<p role="alert" className="form-error mt-5">{error}</p>}</section></main>;
}
