'use client';
import { useState } from 'react';
import Link from 'next/link';
import { CircleHelp, CreditCard, ScanText, Send, CheckCircle2, ArrowRight, Download } from 'lucide-react';
import { Dialog } from './ui';

const steps = [
  { icon: CreditCard, title: 'Get paid', text: 'Connect your PayPal sandbox app in Account. Create a project with a clear scope and USD amount, then share its payment link. The buyer approves in PayPal, returns to the checkout page and chooses Complete & verify payment.' },
  { icon: ScanText, title: 'Check the work with AI', text: 'Open the project’s AI review tab. Upload the actual deliverables and choose Check files with AI. Expand each result to see what is present, what is missing, and the page or line behind the finding.' },
  { icon: Send, title: 'Share the final delivery', text: 'Open Delivery and save a link to the final files in your existing file host. Make sure your client can access it. Files uploaded for AI review are kept in your workspace; they are not automatically sent to the client.' },
  { icon: CheckCircle2, title: 'Ask the client to confirm receipt', text: 'In Delivery, create and copy a receipt link. Share it with the client. They open it, check the files and confirm receipt. Refresh the project to see their acknowledgement beside the verified payment.' },
];

export function UsageGuide({ prominent = false }: { prominent?: boolean }) {
  const [open, setOpen] = useState(false);
  return <>
    <button type="button" className={prominent ? 'button secondary gap-2' : 'text-button inline-flex items-center gap-2 text-xs'} onClick={() => setOpen(true)} aria-label="How to use DeliveryProof">
      <CircleHelp size={prominent ? 17 : 18} aria-hidden="true"/><span className={prominent ? '' : 'hidden sm:inline'}>How to use</span>
    </button>
    <Dialog open={open} onClose={() => setOpen(false)} title="From payment to proof.">
      <p className="mb-5 text-sm leading-relaxed text-muted">You’re the seller. Your client uses the payment and receipt links. Follow these four steps for each project.</p>
      <ol className="grid gap-4">{steps.map(({ icon: Icon, title, text }, index) => <li key={title} className="flex gap-3 rounded-2xl bg-surface p-4"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-paper text-accent"><Icon size={17} aria-hidden="true"/></span><div><h3 className="text-sm font-semibold">{index + 1}. {title}</h3><p className="mt-1.5 text-xs leading-relaxed text-muted">{text}</p></div></li>)}</ol>
      <details className="mt-5 rounded-2xl bg-surface p-4"><summary className="cursor-pointer text-sm font-medium">Trying the app as a judge?</summary><div className="mt-3 grid gap-3 text-xs leading-relaxed text-muted">
        <p>Use a Business sandbox account as the seller and a different Personal sandbox account as the buyer. For an India seller, use a US Personal buyer with USD test funds. Open client links in a separate browser profile so you are not signed in as the seller.</p>
        <p>Create a project with this scope: <strong className="font-medium text-ink">“Deliver a brand guide with a primary colour palette and typography recommendations.”</strong></p>
        <a href="/examples/brand-guide.txt" download className="inline-flex items-center gap-2 text-accent"><Download size={14} aria-hidden="true"/>Download a sample deliverable</a>
        <p>Upload the sample in AI review and run the check. It contains a colour palette and explicitly omits typography. Look for the missing requirement and open the original-file citation. Results are generated by the model each time.</p>
        <p>Finish the PayPal capture on the client payment page; approval alone does not record payment. Then save your delivery URL and test the receipt link. Only the client can acknowledge receipt.</p>
      </div></details>
      <div className="mt-5 flex flex-wrap gap-4 text-xs"><Link href="/account" onClick={() => setOpen(false)} className="inline-flex items-center gap-2 text-accent">Connect PayPal<ArrowRight size={14}/></Link><Link href="/projects" onClick={() => setOpen(false)} className="inline-flex items-center gap-2 text-accent">Open projects<ArrowRight size={14}/></Link></div>
    </Dialog>
  </>;
}
